### ISSUE TITLE
Auto picking wrong deck

### ISSUE THREAD

**Issue by mjmac85** [HearthSim/Hearthstone-Deck-Tracker#2554]
I have two decks that are different by 1 card.  The tracker will sometimes pick the wrong deck and then show a missing card error when it comes into play.  Even when I manually select the deck and turn off auto it tracks it under the wrong deck.  This is after I activate the correct deck.  It still switches.

**Comment by Epix37** [comment]
Is this with v0.15.2?
Please post a log of this happening ([see here](Config.Instance.ConstructedStatsModeFilter == GameMode.Ranked)).

**Comment by mwishum** [comment]
I am experiencing a similar issue where a previous version of a deck keeps showing up and I have to use "Force Full Sync" to make it update to the newer version but even then it can't auto-detect and switch decks correctly (I am using v0.15.2)
@Epix37 that link is broken

**Comment by Epix37** [comment]
Fixed it.

**Comment by mwishum** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/298416/hdt_log.txt)
[hdt_log_1464988407.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/298417/hdt_log_1464988407.txt)
Here are log files in which HDT didn't have the right version selected of my deck (Yogg Hunter 1.1).
It looks like on the first file (hdt_log.txt) it incorrectly found the wrong deck at line 240.

**Comment by mjmac85** [comment]
I am using 0.15.2.  Will be playing some more this weekend and as soon as I see it happening I will post a log.  Sorry for the delay.

**Comment by mjmac85** [comment]
Updated today to v0.15.3  Still having the same issue.  Also how can I remove the stats from the wrong deck?

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/299349/hdt_log.txt)

**Comment by garudajava** [comment]
A similar issue: playing on multiple servers, so making the same deck on more than one (I change the name of the deck by server, so asian one gets 'AS CTHUN PRIEST' while america gets 'AM CTHUN PRIEST' for example.)  However, autodeck detect doesn't check the name of the deck (apparently), and often selects the wrong one, even if I've already manually picked the right one.  This happens at the beginning of each game.

**Comment by tknights2015** [comment]
Experienced this tonight. Selected one deck, with HDT on Auto.  HDT changed decks to a similar deck. Decks have completely different names.  Windows 10 OS
Version 15.6  Log files attached
[hdt_log_1467088971.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/336309/hdt_log_1467088971.txt)

**Comment by jkohvak** [comment]
Hi, I'm currently experiencing this problem with 0.15.10 and it's very frustrating.

The situation is as follows: I have a standard mode **Handlock v1.1** and a wild mode Handlock (**Wandlock v1.0**). When I select Wandlock in HDT, and queue up to wild with Wandlock, HDT automatically selects Handlock v1.1. It writes to the log:

_16:34:32|Info|FullScreenFxHandler.Handle >> Now in queue (21.07.2016 16:34:32)
16:34:32|Info|FullScreenFxHandler.AutoSelectDeckById >> Found selected deck: Handlock
16:34:32|Info|DeckImporter.FromConstructed >> Found 18 decks, 18 new
16:34:32|Warning|FullScreenFxHandler.AutoSelectDeckById >> Could not find deck with matching cards.
16:34:32|Info|FullScreenFxHandler.AutoSelectDeckById >> Switching to selected deck: Handlock + v1.1
16:34:32|Info|MainWindow.SelectDeck >> Switched to deck: Handlock (v1.1)
16:34:32|Info|DeckList.ActiveDeck >> Set active deck to: Handlock (Warlock)_

I've got "Auto" turned off. As said, even when I select the deck manually, HDT overrides that to select the wrong deck.

Originally, Wandlock was cloned from Handlock. I deleted the clone and made a new deck --> bug still happens.

Any help?

**Comment by Epix37** [comment]
This happens because the other deck has the id of the selected deck. Running the constructed importing (`IMPORT > FROM CONSTRUCTED`) should solve your problem.

**Comment by jkohvak** [comment]
You're right, it solved it! (I had to import both decks.) Thank you!

**Comment by cyfex** [comment]
When using the copy and paste function provided by HS, the decks messed up again. It seems HDT mistake the pasted new deck as the copied old deck. Maybe they have the same id? I don't know. Please take a look.
