### ISSUE TITLE
Can't edit deck with a french keyboard

### ISSUE THREAD

**Issue by FitzcairnHS** [HearthSim/Hearthstone-Deck-Tracker#3291]
Hello,

Since there is a new version of HDT i can't edit an older deck to remove and add some new cards. The problem is when i begin to search a card in the database like "bénédiction des rois" for paladin the é is not recognized by HDT it's like the letter doesnt exist. 

The weird thing is i typed roi and it doesnt work too. I checked my langage card settings and french is still primary card language.

But if i search with the work king it's working so it mean even with the french card language it doesnt  work anymore in the search database but the card are still shown in french. Totally weird.

I never had an issue like this before with the older version.

**Comment by dom38fr** [comment]
Hi, I confirm this. Before this new HDT update it was a bit annoying that we couldn't use accentuated letters or even ' like in N'Zoth or "Crabe affamé" but now it's even worse... french language is totally unusable as a quick search and we have to type it in english even though our game and HDT language is set in french (and the search answer displays cards in french).

I hope this will get fixed quite soon because it's a bit annoying, to be honest...

Thanks

**Comment by azeier** [comment]
I think this is the same as https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3277? In which case it'll be fixed with the next update. I'll try to get that out soon.

**Comment by FitzcairnHS** [comment]
It look the same. But in french we have also special letters like é who arent recognized in the search engine.

**Comment by ProfesorX** [comment]
same issue, when you search a card in the deck editor in spanish(mexico) didn't find anything, you need to write the name of the card in english to work. It's a problem because i have the game in spanish, so it's difficult many times to know the name of the card to create the deck

**Comment by FitzcairnHS** [comment]
We're almost in august and the bug is still there and it seem nobody devs care about this problem and HDT who used to be the best hs tracker is almost no use now with this bug. Also the new interface editing is horrible. We need support over there please.

**Comment by azeier** [comment]
There will be a new release today.

**Comment by FitzcairnHS** [comment]
Thank you !

**Comment by riQQ** [comment]
Fixed?

**Comment by azeier** [comment]
Yes ;)

**Comment by FitzcairnHS** [comment]
Yes i confirm :)
